version: "3.5"
services:
  db:
    build: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=rafael
      - POSTGRES_DB=bd_app
    ports:
      - 5555:5432
  backend:
    build: back-end
    links:
      - db
    depends_on:
      - db
    ports:
      - 8989:8080
  frontend:
    build: front-end
    depends_on:
      - backend
    ports:
      - 8080:8080
